services:
  robonet:
    image: robonet-base
    container_name: robonet_$USER
    build:
      context: .
    entrypoint: ["/bin/bash", "-c", "/home/robonet/widowx_envs/scripts/run.sh"]
    environment:
      - DISPLAY=:1
      - USB_CONNECTOR_CHART=/home/real/bridge_ws/src/bridge_data_robot/usb_connector_chart.yml
      - ROBONETV2_ARM=wx250s
      - DATA=/home/robonet/trainingdata
      - EXP=/home/robonet/experiments
      - REALSENSE_SERIAL=_207122078479
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - USE_REALSENSE=true
    user: 1000:1000
    group_add:
      - "46"
      - "44"
      - "27"
    stdin_open: true
    tty: true
    device_cgroup_rules:
      - 'c *:* rmw'
    network_mode: host
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - /home/real/bridge_ws/src/bridge_data_robot/usb_connector_chart.yml:/tmp/camera_connector_chart
      - /etc/localtime:/etc/localtime:ro
      # if you want to be able to edit widowx_envs code without rebuilding the image, this
      # overwrites the widowx_envs directory that was copied in at build time
      - ./widowx_envs/experiments:/home/robonet/experiment
      # /media/harddrive/:/home/robonet/trainingdata  # TODO (YL): better way to mount a local directory
      - ./trainingdata:/home/robonet/trainingdata
      # - ./widowx_envs:/home/robonet/widowx_envs
      - /dev:/dev  # for host tty access

  bridge_data_v2:
    image: robonet-bridge-data-v2
    container_name: robonet_${USER}_bridge_data_v2
    user: robonet:1002
    build:
      context: code/bridge_data_v2
    network_mode: host
    environment:
      - WANDB_API_KEY=putwandbkeyhere
    runtime: nvidia
    volumes:
      - ./widowx_envs:/home/robonet/widowx_envs 
      - ./code/bridge_data_v2:/home/robonet/code/bridge_data_v2
      - ./experiments:/home/robonet/experiments
      - /mount/harddrive/:/home/robonet/trainingdata
